"""Initial migration

Revision ID: 430228955523
Revises: 
Create Date: 2026-01-12 16:37:10.303437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430228955523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('option_e', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempts')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
