"""add_external_id_and_music_drive_to_questions

Revision ID: 4677fc257233
Revises: d796d1a3bb5d
Create Date: 2026-01-15 18:53:47.303061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4677fc257233'
down_revision = 'd796d1a3bb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requer batch mode para alterações de schema
    with op.batch_alter_table('questions', schema=None) as batch_op:
        # Adicionar campo external_id à tabela questions
        batch_op.add_column(sa.Column('external_id', sa.String(length=50), nullable=True))
        
        # Adicionar campo music_drive_url à tabela questions
        batch_op.add_column(sa.Column('music_drive_url', sa.String(length=500), nullable=True))
        
        # Criar índice único para external_id (SQLite não suporta unique constraint diretamente)
        batch_op.create_unique_constraint('uq_questions_external_id', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requer batch mode para alterações de schema
    with op.batch_alter_table('questions', schema=None) as batch_op:
        # Remover constraint e campo external_id da tabela questions
        batch_op.drop_constraint('uq_questions_external_id', type_='unique')
        batch_op.drop_column('external_id')
        
        # Remover campo music_drive_url da tabela questions
        batch_op.drop_column('music_drive_url')
    # ### end Alembic commands ###
