"""add_score_system

Revision ID: d796d1a3bb5d
Revises: 430228955523
Create Date: 2026-01-15 16:35:26.149317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd796d1a3bb5d'
down_revision = '430228955523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar campo total_score à tabela users
    op.add_column('users', sa.Column('total_score', sa.Integer(), nullable=False, server_default='0'))
    
    # Adicionar campo points à tabela quiz_attempts
    op.add_column('quiz_attempts', sa.Column('points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover campo points da tabela quiz_attempts
    op.drop_column('quiz_attempts', 'points')
    
    # Remover campo total_score da tabela users
    op.drop_column('users', 'total_score')
    # ### end Alembic commands ###
